name: chapasdk
description: Chapa flutter library to accept payment via Card, Bank or telebirr etc.
version: 0.0.4
homepage: https://github.com/chapa-et/chapa-flutter

environment:
  sdk: ">=2.19.0<4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  flutter_inappwebview:
  connectivity_plus: ^4.0.2
  fluttertoast:
  mockito:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
